Weight Tree Printing
mitre/hipcheck pull request #170
Opened 2024-07-01 20:01 UTC by vcfxb

Provide CLI functionality to print the resolved weights used in analysis. 

Closes #28

2024-07-01 20:07 UTC, alilleybrinker commented
Testing locally now!

2024-07-01 20:11 UTC, alilleybrinker requested changes
Rename to `hc scoring`, otherwise LGTM!

2024-07-01 20:13 UTC, alilleybrinker approved these changes

2024-07-01 20:58 UTC, vcfxb commented
It took 2 attempts at squashing and force-pushing but I think this is finally properly squashed and ready to merge.

2024-07-02 03:12 UTC, alilleybrinker approved these changes

2024-07-02 03:12 UTC, merged