docs: added README for dockerhub
mitre/hipcheck pull request #255
Opened 2024-08-06 18:11 UTC by patrickjcasey

2024-08-06 18:45 UTC, alilleybrinker requested changes
Thanks @patrickjcasey! I have a few nitpick comments that should be quick fixes.

As for the location of the file, I'm inclined to instead name any top-level folder with files necessary for distributing Hipcheck something like `dist/`. This would keep with the generally short naming convention of other top-level folders. Within that folder, it would probably be good to split up the content based on the use, so putting it at `dist/dockerhub/README.md` would make sense.

Regarding the Category topic, I've pinged Amndeep to see if he can set the "Security" category for us.

2024-08-06 18:45 UTC, alilleybrinker commented on third-party-docs/README-dockerhub.md
> +# What is hipcheck?
Nitpick: "hipcheck" should be capitalized as "Hipcheck"

2024-08-06 18:45 UTC, alilleybrinker commented on third-party-docs/README-dockerhub.md
> +## How to use the image
Nitpick: Consistent capitalization with other headers would make this "How to Use the Image"

2024-08-06 18:45 UTC, alilleybrinker commented on third-party-docs/README-dockerhub.md
> +Hipcheck's software is licensed under the Apache 2.0 license, which can be
Nitpick: There should be an empty line between headers and paragraphs.

2024-08-06 18:47 UTC, alilleybrinker commented
Oh, and we probably should just use this GitHub Action (https://github.com/peter-evans/dockerhub-description) for setting the description. Under the hood it uses a Docker Hub API token to make the relevant API call for setting the description. This way we can update it ourselves whenever we need to instead of needing to ping Amndeep.

2024-08-06 19:20 UTC, patrickjcasey commented
I preliminarily added the job to CI to automatically update the description. I don't think there is a way to test it works without actually pushing something to dockerhub. Also, I was not 100% certain that dockerhub credentials are the same as the credentials used for the docker cli

2024-08-06 19:21 UTC, patrickjcasey commented
Also it should be noted somewhere that dockerhub limits the description to 25,000 bytes and the github-action plugin we are using automatically performs the truncation if necessary

2024-08-06 22:43 UTC, alilleybrinker commented
> Also it should be noted somewhere that dockerhub limits the description to 25,000 bytes and the github-action plugin we are using automatically performs the truncation if necessary

Good to note. We probably ought to error out rather than silently truncating. Likely means checking the byte length ourselves.

2024-08-09 16:41 UTC, alilleybrinker approved these changes

2024-08-09 16:41 UTC, merged

2024-08-09 16:41 UTC, alilleybrinker commented
Thanks @patrickjcasey! :tada: