allow manifest field of plugins to be a path
mitre/hipcheck pull request #505
Opened 2024-10-18 22:01 UTC by patrickjcasey

This pull request accomplishes 2 main goals:

1. It centralizes the location where all of the LEGACY "plugins" are managed, making it easier in the future to update the codebase to reflect when these features have been updated to use the plugin APIs
2. Adds the ability to run locally built plugins via a provided filepath, allowing for testing plugins, without the need for relying on downloading plugins and their manifests. This is especially useful right now, as the infrastructure for downloading plugins is not currently in place.

This pull request also cleans up a couple of small items in the codebase:

1. The `activity` plugin removed `mock_engine` from its `dependencies` and added it to its `dev-dependencies`, as it is only a dependency for testing and should not be running in the context of a normal `activity` plugin binary
2. Cleaned up some log messages to more accurately reflect the current state of the codebase

2024-10-21 12:52 UTC, j-lanson commented on hipcheck/src/analysis/score.rs
> -			FUZZ_PHASE => db.fuzz_analysis(),
I would actually restore these two deleted lines from the match statement. the above `&& MITRE ...` does the check.

2024-10-21 12:53 UTC, j-lanson commented
Have you run an analysis including `fuzz` and `activity` using this version of the codebase?

2024-10-22 13:49 UTC, patrickjcasey commented
I have not tried to run an analysis with `fuzz` and `activity` enabled

2024-10-22 15:00 UTC, patrickjcasey commented
Here is the output from running the following command `cargo run -- check --policy Hipcheck.kdl https://github.com/mitre/hipcheck.git`

Here is the `Hipcheck.kdl` used:
cargo run -- check --policy Hipcheck.kdl https://github.com/mitre/hipcheck.git

Both `fuzz` and `activity` were enabled for this test and had no issues

2024-10-22 15:27 UTC, j-lanson requested changes
See comment

2024-10-22 15:31 UTC, patrickjcasey commented
added them to the repo!

2024-10-22 15:32 UTC, j-lanson commented
<img width="851" alt="legacy" src="https://github.com/user-attachments/assets/2433c73c-f139-4239-8506-891255c1c81b">

On my side the analysis completed even with the missing files, and my print line shows its still using the legacy analysis function instead of the plugin.

2024-10-22 15:35 UTC, j-lanson commented
Please make it so that a missing manifest file results in a failed analysis, and double-check that you are running a plugin and not a legacy analysis function

2024-10-25 21:34 UTC, closed without merging