feat: added support for running "mitre/activity" as a plugin
mitre/hipcheck pull request #556
Opened 2024-10-31 21:05 UTC by patrickjcasey

This pull requrest adds support for running `mitre/activity` via the new plugin infrastructure and tweaks the default config `config/Hipcheck.kdl` to enable running this plugin via the default config

During the development of this feature, I hit a couple of `unreachable!()` blocks in the code that evaluates policy expressions, so I added a new error type `MismatchedTypes(Box<Primitive>, Box<Primitive>, String)` to `hipcheck/src/policy_exprs/errors.rs` to make it clearer when mismatched types are compared

To make it easier for users to work with timestamp data, specifically when working with `jiff::Span` and `jiff::Zoned` and will allow us to more easily enable custom JSON objects that are opaque to the user in the future

2024-11-01 16:25 UTC, j-lanson requested changes
Looks good, just one change because of broader project context

2024-11-01 16:25 UTC, j-lanson commented on hipcheck/src/policy_exprs/env.rs
> +		)),
I think I would suggest reverting all of these changes associated with the `MismatchedTypes` variant, and remove the variant. The PR #514 will make this change obsolete, and merging it now will just cause conflicts with that PR.

2024-11-01 16:50 UTC, j-lanson commented
Resolves #545 .

2024-11-02 21:59 UTC, patrickjcasey commented
Should be good to go!

2024-11-04 13:28 UTC, j-lanson approved these changes

2024-11-04 13:28 UTC, merged