feat: implemented submit chunking for RFD #0010
mitre/hipcheck pull request #737
Opened 2024-12-20 16:36 UTC by patrickjcasey

- Added support for chunking Query submissions
- Added test for submission chunking

I just want to ensure that adding an enum variant to `QueryState` is not considered a breaking change. Also since this changes `hipcheck-common`, does its version need be incremented or do we just handle that when it comes time to cut a release

2024-12-20 16:39 UTC, patrickjcasey commented
closes #730 #732

2024-12-23 13:36 UTC, j-lanson requested changes
Missing some logic in the QuerySynthesizer, but the rest is looking good!

2024-12-23 13:36 UTC, j-lanson commented on hipcheck-common/src/chunk.rs
> +					}
I believe the `QuerySynthesizer` needs to be modified as well to support de-chunking chunked `Submit` queries.

2024-12-23 13:36 UTC, j-lanson commented on hipcheck-common/src/chunk.rs
> +		}
To ensure the above `QuerySynthesizer` is implemented correctly, perhaps there should be an additional stage to this test that tries to reassemble the original message from the fragments.

2024-12-23 13:36 UTC, j-lanson commented on sdk/rust/src/error.rs
> +			UnexpectedRequestInProgress => Error::UnexpectedReplyInProgress,
Should add another variant to `Error` instead of re-using `UnexpectedReplyInProgress`

2024-12-23 13:52 UTC, j-lanson commented
On the subject of versioning, I would do the following:

1. Bump `hipcheck-common` version to `0.2.0`
2. Update `rust-sdk` to take the new version, and bump it's version to `0.3.0`
3. Update the plugins to take SDK `0.3.0`

We can add RFD10 to `hipcheck-common-v0.2.0` without another version bump since we haven't released anything yet.

On the next release, we will release new versions of the rust SDK and all plugins.

2024-12-23 17:15 UTC, patrickjcasey commented
I applied the fixes you suggested and fixed a couple of minor issues with usage of `serde_json`. The `from_str` and `to_string` methods were being used when  directly assigning to a `serde_json::Value` and calling `serde_json::Value::from_value` was more appropriate

2024-12-23 17:37 UTC, patrickjcasey commented
This is not quite done yet, still working through a couple of things

2025-01-10 15:27 UTC, patrickjcasey commented on hipcheck-common/src/chunk.rs
> +			i += 1;
I was attempting to maintain concern ordering, but the original approach is better because it is able to potentially pack non-consecutive concerns in one message, potentially reducing total # of messages. I reverted this portion of the commit to use the original logic

2025-01-10 15:42 UTC, patrickjcasey commented
just pushed to this branch again. It seems like there were some new `clippy` warnings that popped up, so I also fixed those

2025-01-10 15:43 UTC, alilleybrinker commented
> just pushed to this branch again. It seems like there were some new `clippy` warnings that popped up, so I also fixed those

Makes sense, Rust released 1.84.0 yesterday, which we pick up immediately in CI. New Rust versions usually mean new Clippy lints.

2025-01-10 19:27 UTC, j-lanson approved these changes
Thanks Patrick!

2025-01-10 19:27 UTC, merged